### ISSUE TITLE
No Content-Length in ctx.ServeFile method

### ISSUE THREAD

**Issue by genedna** [go-macaron/macaron#100]
In the `ctx.ServeFile()` function, it has no header  value for `Content-Length`:

```
ctx.Resp.Header().Set("Content-Description", "File Transfer")
ctx.Resp.Header().Set("Content-Type", "application/octet-stream")
ctx.Resp.Header().Set("Content-Disposition", "attachment; filename="+name)
ctx.Resp.Header().Set("Content-Transfer-Encoding", "binary")
ctx.Resp.Header().Set("Expires", "0")
ctx.Resp.Header().Set("Cache-Control", "must-revalidate")
ctx.Resp.Header().Set("Pragma", "public")
```

Should have it?

**Comment by Unknwon** [comment]
No, I think stdlib does that for us https://github.com/golang/go/blob/9f7ea616742f8d58ecc140afcb0fa53bcb84fe9b/src/net/http/fs.go#L262

**Comment by genedna** [comment]
OK, but this segment only execute when not set the `Content-Encoding` value in HTTP Header, or I set 'Content-Encoding' after `ServeContent` method.

**Comment by Unknwon** [comment]
I don't understand, Macaron didn't set `Content-Encoding` in `ctx.ServeFile()`.
