### ISSUE TITLE
Rendering templates fails under high load

### ISSUE THREAD

**Issue by am4** [go-macaron/macaron#101]
Recently I've encountered a strange bug. Under high load some templates were rendered twice or even more times. I tried to trace the bug and it turned out that sometimes the method `writeTo` (https://github.com/go-macaron/macaron/blob/master/render.go#L564) returned error.
Apparently when the aforementioned method fails, the buffer isn't reset. https://github.com/golang/go/blob/0104a31b8fbcbe52728a08867b26415d282c35d2/src/bytes/buffer.go#L224
Here's a possible fix for this issue.
```go
if _, err := out.WriteTo(r); err != nil {
    out.Reset()
}
```

**Comment by Unknwon** [comment]
Thanks! Fix pushed.
