### ISSUE TITLE
平滑升级需求

### ISSUE THREAD

**Issue by Yanjunhui** [go-macaron/macaron#103]
无闻大神 可否增加一个平滑升级的功能  
现在每次升级都要自己kill进程然后再覆盖文件 手动执行 
能不能增加平滑升级支持 感恩~

**Comment by Yanjunhui** [comment]
https://github.com/tabalt/gracehttp  找到一个类似的包 但是不知道怎么跟macaron结合

**Comment by piaohailin** [comment]
这种方式好危险，相当于暴漏一个rul，万一被黑了。。哈哈

**Comment by Unknwon** [comment]
我觉得还是用 NGINX 代理切换更方便。。做这样的功能我觉得属于吃力不讨好。。
