### ISSUE TITLE
Value not found for type *context.Context

### ISSUE THREAD

**Issue by joefazee** [go-macaron/macaron#107]
How do i extend the *macaron.Context?

I have this

`type Context struct {
	*macaron.Context
}
`

and in my router method i used it just like the normal macaron Context
`func HomePage(ctx *context.Context) string  {
	return "Hello"
}`

The same thing happened when i tried to inject session modules.

**Comment by Unknwon** [comment]
You have to `ctx.Map` before using it: https://go-macaron.com/docs/advanced/custom_services
