### ISSUE TITLE
ctx.JSONString格式转换不能自定义输出格式吗？

### ISSUE THREAD

**Issue by piaohailin** [go-macaron/macaron#108]
例如：
RoleName: "系统管理员",
Roleid: 1,
变成
roleName: "系统管理员",
roleid: 1,

因为与移动端人员对接过程中他们习惯驼峰法首字母小写。
如果在写模型结构体首字母小写就导不出来了。

**Comment by Unknwon** [comment]
See https://gobyexample.com/json...
