### ISSUE TITLE
code repeated 

### ISSUE THREAD

**Issue by DrWrong** [go-macaron/macaron#111]
In the file `router.go` https://github.com/go-macaron/macaron/blob/master/router.go#L182
```golang

c := r.m.createContext(resp, req)
c.params = params
c.handlers = make([]Handler, 0, len(r.m.handlers)+len(handlers))
c.handlers = append(c.handlers, r.m.handlers...)
c.handlers = append(c.handlers, handlers...)
c.run()
```

However in the file `macaron.go`  https://github.com/go-macaron/macaron/blob/master/macaron.go#L149

```golang
	c := &Context{
		Injector: inject.New(),
		handlers: m.handlers,
		action:   m.action,
		index:    0,
		Router:   m.Router,
		Req:      Request{req},
		Resp:     NewResponseWriter(rw),
		Render:   &DummyRender{rw},
		Data:     make(map[string]interface{}),
}

```
why `c.handlers` is set to `m.handlers` twice? I am quite confusing

**Comment by Unknwon** [comment]
Good question!

In `macaron.go`, `handlers` must be set to make the newly created `context` to be valid and usable. But that does not mean after creation, we can't change the default settings.
