### ISSUE TITLE
what is the context.action use for

### ISSUE THREAD

**Issue by DrWrong** [go-macaron/macaron#112]
in the `macaron.go`
```golang
// Action sets the handler that will be called after all the middleware has been invoked.
// This is set to macaron.Router in a macaron.Classic().
func (m *Macaron) Action(handler Handler) {
	validateHandler(handler)
	m.action = handler
}

```

you say `action` is set to `macarion.Router`

Howerver codes are 

```golang
m := &Macaron{
		Injector: inject.New(),
		action:   func() {},
		Router:   NewRouter(),
		logger:   log.New(out, "[Macaron] ", 0),
}
``` 

`action` is just set to a none process function

so what's the action is use for? why not just remove it ?

**Comment by Unknwon** [comment]
Because you should use it only if you want to clean up something after all handlers are executed, which means by default there is nothing to cleanup.
