### ISSUE TITLE
Equivalent Config for Apache "DocumentRoot "  in Macaron ?

### ISSUE THREAD

**Issue by toni-moreno** [go-macaron/macaron#113]
There is no way to change my html root path in https://github.com/toni-moreno/snmpcollector/blob/master/pkg/webserver.go#L52-L63

When I've changed "public" ( which is now at current working directory ) by a absolute path like /usr/share/snmpcollector/ (where public directory is)  , it can not find the root path.  

I  can not find on https://gowalker.org/gopkg.in/macaron.v1 any reference on how can I change the RootPath.... Can you help me please?

**Comment by Unknwon** [comment]
I think this is the `Root` you're looking for: https://gowalker.org/gopkg.in/macaron.v1#_variables
