### ISSUE TITLE
nginx静态文件无效

### ISSUE THREAD

**Issue by GanWenpeng** [go-macaron/macaron#116]
我用nginx将请求转发到了Macaron的端口，发现每次请求哪怕是.css、.js、.png这样的静态文件的状态码都是200而不是304，后来在nginx上将静态文件的请求全部转发到static文件夹下去，直接就404了，请问您知道是什么原因吗？

**Comment by Unknwon** [comment]
404 说明你路径配置错了。Macaron 请求 URL 是不包含根目录 static 的，你要区别清楚。。
