### ISSUE TITLE
Switch from MD5 to PBKDF2 for AES keys

### ISSUE THREAD

**Issue by aaronjwood** [go-macaron/macaron#118]
I'd like to propose that Macaron switch from using MD5 to PBKDF2 for its AES keys https://github.com/go-macaron/macaron/blob/78521e4647ad5dcbabd5734d94582ca2373cbad8/context.go#L443

I think using MD5 to generate AES keys has some serious flaws. For example, there's a good chance that someone could figure out the AES key in a few seconds if they have a good rainbow table. Also, you can generate MD5 hashes like crazy on consumer-level GPUs (1-5 billion hashes per second easy on a SINGLE GPU that's less than $500) so the key becomes very easy to attack. PBKDF2 is slow (key stretching) and specifically designed for this use case since it's a key derivation function.

Related to https://github.com/gogits/gogs/issues/4117

**Comment by aaronjwood** [comment]
https://github.com/Unknwon/com/issues/11 is slightly related to this.

**Comment by aaronjwood** [comment]
Do you want to use AES-128 or AES-256 for this? If I generate a 16-byte key via PBKDF2 that'll be AES-128. 32 byte key will be AES-256. Also, how do you want to handle the salt? Where would you be feeding that from? Can I assume that it'll be sent from the caller so that we can change the signature to `func (ctx *Context) SetSuperSecureCookie(secret, salt, name, value string, others ...interface{})`?

**Comment by Unknwon** [comment]
>Do you want to use AES-128 or AES-256 for this?

I think `AES-256` is good.

>Also, how do you want to handle the salt? Where would you be feeding that from?

The secret from Gogs is `slat + password`, and change API is not a good idea..

**Comment by aaronjwood** [comment]
Sounds good.

PBKDF2 needs the password, salt, iteration count, key length, and a hash function as its inputs. If we change the signature here can we just change Gogs to pass things in separately? I can't pass the salt+password as a single parameter to PBKDF2.

**Comment by Unknwon** [comment]
>I can't pass the salt+password as a single parameter to PBKDF2.

In that case... I think we should use something simple in Macaron, but write Gogs's version of `SetSuperSecureCookie` so we don't need to care about API breaks.

**Comment by aaronjwood** [comment]
Hmm, okay so what do you want to do for Macaron? Just switch to SHA2 for now?
When you say write Gogs's version do you mean to just edit the vendor that's committed as part of the repo itself?

**Comment by Unknwon** [comment]
>Hmm, okay so what do you want to do for Macaron? Just switch to SHA2 for now?

Yes, I think so.

>When you say write Gogs's version do you mean to just edit the vendor that's committed as part of the repo itself?

Not vendor, but somewhere [here](https://github.com/gogits/gogs/blob/master/modules/context/context.go#L43), this is very specific to codebase, for example:

```go
// modules/context/context.go

// Context represents context of a request.
type Context struct {
    ...
}

func (ctx *Context) SetSuperSecureCookie(secret, salt, name, value string, others ...interface{}) {
    ... // Gogs's version of function
}
```

**Comment by Unknwon** [comment]
Just to check, is the PR coming soon? Because right now users are not able to compile Macaron...

**Comment by aaronjwood** [comment]
Just opened https://github.com/go-macaron/macaron/pull/120

**Comment by Unknwon** [comment]
I guess this can be closed?
