### ISSUE TITLE
Redirect with 301 if static file URL has '/' suffix

### ISSUE THREAD

**Issue by Zeno-Code** [go-macaron/macaron#124]
如果用 http.Handle("/", http.FileServer(http.Dir("./")))
test.jpg/ 是 301 到 test.jpg

**Comment by Unknwon** [comment]
请提供示例代码。

**Comment by Zeno-Code** [comment]
`func main() {
	m := macaron.Classic()
	m.Use(macaron.Renderer())
	m.Get("/", func(ctx *macaron.Context) {
		ctx.HTML(200, "index")
	})
	m.Get("/hello/:id", func(ctx *macaron.Context) {
		ctx.HTML(200, "index")
	})
	m.Run(80)
}`

以上就是帮助文档提供的最简单示例

/hello/123
/hello/123/

是否有移除尾部斜杠的办法?

![qq 20170226104253](https://cloud.githubusercontent.com/assets/25820304/23336625/616b8004-fc10-11e6-903f-d0165f94257c.jpg)

**Comment by Unknwon** [comment]
... 你这是什么前端应用。。为什么会带有斜杠。。

**Comment by Zeno-Code** [comment]
这里先感谢一下无闻老师的教程

就是浏览器的访问,以前是写PHP的,有个经典的漏洞是pathinfo没处理好,静态文件后面带斜杠有风险
刚开始学go,我就随便了个斜杠上去,发现只用 http 包,返回301, 但是 macaron 就是200 了
还有路由器没有提到对尾部斜杠的处理,搜索引擎可能会当作两个路径来处理

我感觉应该是在建立 tree 的时候出的状况

**Comment by Unknwon** [comment]
那 200 到底返回了什么具体内容？。。。

**Comment by Zeno-Code** [comment]
静态文件和路由页面是否有尾部斜杠,返回的都是一模一样的内容
![qq 20170226105840](https://cloud.githubusercontent.com/assets/25820304/23336709/a46e5276-fc12-11e6-9d72-dfd1fccd6be6.jpg)

**Comment by Unknwon** [comment]
嗯。。有点道理。。我看看

**Comment by Zeno-Code** [comment]
补充一下,我用的是 go 1.8

**Comment by Unknwon** [comment]
我觉得框架做此类限制不合适，但是如果你要实现特定需求，可以参考以下代码：

```go
package main

import (
	"net/http"
	"strings"

	"gopkg.in/macaron.v1"
)

func main() {
	m := macaron.Classic()
	m.Before(func(rw http.ResponseWriter, req *http.Request) bool {
		if strings.HasSuffix(req.URL.Path, "/") {
			http.Redirect(rw, req, strings.TrimRight(req.URL.Path, "/"), 301)
			return true
		}
		return false
	})
	m.Use(macaron.Renderer())
	m.Get("/hello/:id", func(ctx *macaron.Context) string {
		return "hello world"
	})
	m.Run(8080)
}
```
