### ISSUE TITLE
Support to run over HTTPS

### ISSUE THREAD

**Issue by jeffprestes** [go-macaron/macaron#128]
Real and serious web applications need to run over HTTPS. So, how could I start a Macaron instance over HTTPS? I didn't find any docs explaining how to do it. It seems the Macaron has this lack of functionality. Am I right? My team had to create the following workaround:

macaron.go
``` 
// Run the http server. Listening on os.GetEnv("PORT") or 4000 by default.
func (m *Macaron) Run(args ...interface{}) {
	host, port := GetDefaultListenInfo()
	var fullchain, privateKey string
	if len(args) == 1 {
		switch arg := args[0].(type) {
		case string:
			host = arg
		case int:
			port = arg
		}
	} else if len(args) >= 2 {
		if arg, ok := args[0].(string); ok {
			host = arg
		}
		if arg, ok := args[1].(int); ok {
			port = arg
		}
		if arg, ok := args[2].(string); ok {
			fullchain = arg
		}
		if arg, ok := args[3].(string); ok {
			privateKey = arg
		}
	}

	addr := host + ":" + com.ToStr(port)
	logger := m.GetVal(reflect.TypeOf(m.logger)).Interface().(*log.Logger)
	logger.Printf("listening on %s (%s)\n", addr, safeEnv())
	if len(fullchain) > 5 {
		logger.Fatalln(http.ListenAndServeTLS(addr, fullchain, privateKey, m))
		return
	}
	logger.Fatalln(http.ListenAndServe(addr, m))
}
```
main.go
```
if port == 443 {
		app.Run("0.0.0.0", port, getFullchainPemFilePath(), getPrivatekeyPemFilePath())
		return
	}
```
Is there an alternative? Or should we send a PullRequest with a new RunOverTLS function to be added into macaron package?
We'll be glad to help the project. We just want to avoid duplicated work if an existent solution already have been in place.
Cheers!

**Comment by veecue** [comment]
`macaron.Run()` is a very simple function for debug purposes. As soon as you want something more complex (like listening on a unix socket, (f)cgi, tls, etc.) you can use the standard library to listen and then use macarons `http.Handler` interface to pass the requests to it.

**Comment by unknwon** [comment]
I totally agree with @veecue and supporting HTTPS just adds unnecessarily more complexity that would defeat the purpose of `m.Run`. Please use [`http.ListenAndServeTLS()`](https://pkg.go.dev/net/http#ListenAndServeTLS) instead.
