### ISSUE TITLE
Binding "Required" on boolean throws required message when is false

### ISSUE THREAD

**Issue by sbengo** [go-macaron/macaron#130]
Hi,

We set a `Required` binding on the following boolean field: 
````
IsMultiple  bool   `xorm:"is_multiple" binding:"Required"`
````

The different cases of:
- When the value is true, no error is thrown - OK.
- When the value is false, an error is thrown with the following message - NOOK:

````
{fieldNames: ["IsMultiple"], classification: "RequiredError", message: "Required"}
````

According to the docs, `Required: Must be non-zero value`, it shouldn't throw an error, right?

Thanks,
Regards

**Comment by toni-moreno** [comment]
Again happens an related with  boolean binding verifications. (https://github.com/toni-moreno/snmpcollector/issues/209) 
 
When I set 
```
	ConcurrentGather bool `xorm:"'concurrent_gather' default 1" binding:"Default(1)"`
````
And I do binding with GoncurrentGather = false in Json stream  , binding returns ConcurrentGather=1

We can not do binding verifications with boolean data.

**Comment by Unknwon** [comment]
@sbengo `false` is the zero value for `bool` in Go, so based on the docs, code works as expected.

@toni-moreno I don't very understand your example? In Go, true is true, false is false, there is no number maps to true or false.

**Comment by Unknwon** [comment]
@sbengo in practice, if a bool value is not presented, I treat as false, so `Required` is really not useful for `bool` type.
