### ISSUE TITLE
Add the Casbin authorization middleware for Macaron

### ISSUE THREAD

**Issue by hsluoyz** [go-macaron/macaron#131]
Hi @Unknwon ,

first thanks for creating such a great project!

I'm the author of [Casbin](https://github.com/casbin/casbin). It is a Go authorization library that supports access control models like ACL, RBAC, ABAC. See details here: https://github.com/casbin/casbin

I think Macaron is a very promising web framework, so I have developed an authz middleware for Macaron here: https://github.com/casbin/macaron-authz

And I want to ask if Macaron-authz can be listed under the README here: https://github.com/go-macaron/macaron#middlewares

It's better if you can put the entire repo in: https://github.com/go-macaron, and rename it to authz. You can give me rights for this repo so I can maintain it.

Thanks!

**Comment by Unknwon** [comment]
Hi, thanks for asking!

I can add you to **go-macaron** organization and transfer https://github.com/casbin/macaron-authz, if that's better/easier for you?

**Comment by hsluoyz** [comment]
> I can add you to go-macaron organization and transfer https://github.com/casbin/macaron-authz, if that's better/easier for you?

Yes, it's the better way. Please add me. Thanks for the integration!

**Comment by Unknwon** [comment]
OK, I've sent invitation, but not sure if it's possible for you to make repository transfer.

**Comment by hsluoyz** [comment]
I didn't see the invitation in GitHub web or my mailbox, could you resend it? thanks.

**Comment by Unknwon** [comment]
Sent!

**Comment by hsluoyz** [comment]
I can't create a repo in the org, please create a repo named ``authz``, then I should have the write permission.

**Comment by Unknwon** [comment]
I have added you to https://github.com/go-macaron/authz.

**Comment by hsluoyz** [comment]
Thanks! The repo is almost done, Can you switch on Travis CI here: https://travis-ci.org/go-macaron/authz

**Comment by Unknwon** [comment]
Done. :+1:

**Comment by hsluoyz** [comment]
Nice cooperation! 👍

**Comment by hsluoyz** [comment]
BTW, this PR: https://github.com/go-macaron/macaron/pull/132 added the middleware to readme.
