### ISSUE TITLE
Question: Routers with and without specific middlewares

### ISSUE THREAD

**Issue by FabianWilms** [go-macaron/macaron#134]
Hello!

I really like the concept of macaron and would love to use it in one of my products, but I'm having a hard time to implement the following:

I want to have endpoints with differenct security levels and checks. Some endpoints don't need any security, for some it's enough to be authenticated and for others there is some more complex logic needed to be allowed to access them.
I wanted to write different middlewares for these requirements.

Now to the question: 

### How can I have middlewares only active for some endpoints?

Kind regards,
Fabian

**Comment by Unknwon** [comment]
Hi! You can use group routing: https://go-macaron.com/docs/middlewares/routing#group-routing
