### ISSUE TITLE
每次更新可以打下版本标签吗

### ISSUE THREAD

**Issue by rsinensis** [go-macaron/macaron#139]
既然代码用gopkg管理，版本标签都没及时更新，导致我都自己改源码。
能每次更新可以打下版本标签吗？
或者现在dep可以用了，能否把gopkg去掉
```
gopkg.in/ini.v1       
gopkg.in/macaron.v1
```

**Comment by Unknwon** [comment]
不见得每个提交都是跟代码有关的。。文档改动什么的一般不会打 tag，其他的都会。
