### ISSUE TITLE
Intercept route response in middleware

### ISSUE THREAD

**Issue by joesonw** [go-macaron/macaron#141]
Is there any way to intercept and modify response from route?

E.g,

route respond a json string `{"user_id": 1}`

In my middleware, i want it to be `{"data":{"user_id": 1},"code":0}` before returning to client

Is this feature available now? Or should I implement it by wrapping my own `Context`

**Comment by myml** [comment]
m.Use(func(ctx *macaron.Context) {
		ctx.Next()
		if err, ok := ctx.Data["err"]; ok {
			ctx.JSON(200, &Result{Err: err})
		} else {
			ctx.JSON(200, &Result{Result: ctx.Data["result"]})
		}
	})
	m.Get("/user", func(ctx *macaron.Context) {
		u, err := user.Current()
		if err != nil {
			ctx.Data["err"] = err
			return
		}
		ctx.Data["result"] = u
	})

I did that
