### ISSUE TITLE
无闻老师请见问题

### ISSUE THREAD

**Issue by jossion** [go-macaron/macaron#142]
我按照您Macaron官网的指引 用go get gopkg.in/macaron.v1时报错信息如下：
$ go get gopkg.in/macaron.v1
package golang.org/x/crypto/pbkdf2: unrecognized import path "golang.org/x/crypto/pbkdf2" (https fetch: Get https://golang.org/x/crypto/pbkdf2?go-get=1: net/http: TLS handshake timeout)
请教一下如何处理？

**Comment by Unknwon** [comment]
应该是要翻墙的意思。。。
