### ISSUE TITLE
同样的hello，还是有点差距

### ISSUE THREAD

**Issue by sblig** [go-macaron/macaron#143]
![image](https://user-images.githubusercontent.com/1748000/30518417-61e5b2b2-9bb0-11e7-81ed-7e97600ac5bb.png)
`func main(){
	m := macaron.Classic()
	m.Get("/",func() string{
		return "Hello world!"
	})
	m.Run()
	
}`

go
`func main() {
	http.HandleFunc("/",func(w http.ResponseWriter,r *http.Request){
		w.Write([]byte("hello,this is version 1!"))
	})

	log.Fatal(http.ListenAndServe(":4001",nil))
}
`

**Comment by sblig** [comment]
ab -n 100000 -c 1000 http://localhost:4001/

**Comment by Unknwon** [comment]
So..... then what?
