### ISSUE TITLE
Anonymise IPs in logger

### ISSUE THREAD

**Issue by veecue** [go-macaron/macaron#145]
Hi there,
in Germany, for logging IP addresses, it is necessary to truncate the last 2 bytes for IPv4 and the last 8 bytes for IPv6 addresses. Can you add an option to the logger to create this behaviour?
Greetings

**Comment by Unknwon** [comment]
Hi... the default logger is just a simple example of how to log requests/responses, you can always make one fits your need and replace the default, that is the power of the Macaron...
