### ISSUE TITLE
Add Support to autocert as default HTTPS

### ISSUE THREAD

**Issue by jeffprestes** [go-macaron/macaron#147]
Nowadays every webserver must run over HTTPS (TLS). Golang Autocert automatically generates and manages Let's Encrypt certs. The method below is a suggestion to include to Macaton struct to be very easy to all Go-Macaron users run their web applications over HTTPS:
```
// RunWithAutoCert the http server with Let's Encrypt Cert automatically generated. Listening 443 by default.
func (m *Macaron) RunWithAutoCert() {
	host, port := GetDefaultListenInfo()
	port = 443
	addr := host + ":" + com.ToStr(port)
	logger := m.GetVal(reflect.TypeOf(m.logger)).Interface().(*log.Logger)
	server := &http.Server{
		Addr:    addr,
		Handler: m,
	}
	certManager := autocert.Manager{
		Prompt: autocert.AcceptTOS,
		Cache:  autocert.DirCache("certs"),
	}
	server.TLSConfig = &tls.Config{
		GetCertificate: certManager.GetCertificate,
	}
	logger.Printf("listening HTTPS on %s (%s)\n", addr, safeEnv())
	logger.Fatalln(server.ListenAndServeTLS("", ""))
}
```

**Comment by Unknwon** [comment]
Hi, which package does `autocert` come from?

**Comment by jeffprestes** [comment]
From Golang X Projects: "golang.org/x/crypto/acme/autocert"

More details here: https://godoc.org/golang.org/x/crypto/acme/autocert

I think it might helps devs uses Macaron and want to use Let's Encrypt in order to run their Macaron's project under HTTPS for free.

**Comment by Unknwon** [comment]
Thanks for the info!

It is a good idea to add, but I found [this comment](https://github.com/golang/crypto/blob/master/acme/autocert/autocert.go#L8) so I think we probably need to wait until it becomes stable?

**Comment by Unknwon** [comment]
Hmm, I still need to find out what's the minimum Go version to use this package. Also, Caddy has automated HTTPS with free certificate from let's encrypt. 

The initial addition of this feature could just for convenience. However, the framework will be responsible for the rest of its lifetime to maintain this feature. That's the main concern.

**Comment by jeffprestes** [comment]
Caddy uses the same mechanism/library, that's why I am advocating to add
this to Macaron because the library is stable.
IMHO, their developers only add that disclaimer to avoid any kind of legal
issues than they are not secure the lib is OK to use.

**Comment by Unknwon** [comment]
Thanks, I'll add to codebase then I have time.

**Comment by guysmoilov** [comment]
@jeffprestes Thanks for making this, I also find myself needing to use Let's Encrypt. Is the above code everything that's needed? (I assume the call should be inserted in cmd/web.go, just before the `server.ListenAndServeTLS` call)

**Comment by jeffprestes** [comment]
@guysmoilov I agree. 
Would you mind edit it and send a PR?

**Comment by guysmoilov** [comment]
@jeffprestes I ended up putting this thing on hold, since it required updating golang.org/x/crypto in vendor files, as the current version in the project doesn't include autocert. I'm not sure what are the wider consequences of doing this, and so it's probably better to wait with the PR until vendor files are updated...

**Comment by humaidq** [comment]
[gin-gonic/autotls](https://github.com/gin-gonic/autotls) would work. It uses `golang.org/x/crypto/acme/autocert`.  

```go
package main

import (
	"github.com/gin-gonic/autotls"
	"gopkg.in/macaron.v1"
	"log"
)

func main() {
	m := macaron.Classic()
	m.Get("/", func() string {
		return "Hello world!"
	})
	log.Fatal(autotls.Run(m, "example1.com", "example2.com"))
}
```

**Comment by jeffprestes** [comment]
Thanks @humaidq 

I am going to try your suggestion and let you know.

**Comment by jeffprestes** [comment]
Sorry @humaidq but it's not working. autotls from Gin guys are outdated and returning this error:
```http: TLS handshake error from 191.254.73.60:49256: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.``` 
Also, there's an open issue: https://github.com/gin-gonic/gin/issues/2135 
Again thanks for trying to help us.

**Comment by jeffprestes** [comment]
Let autocert go guys. 
CertMagic ( https://github.com/mholt/certmagic ) is working perfectly
```go 
package main

import (
	"github.com/mholt/certmagic"
	"gopkg.in/macaron.v1"
	"log"
)

func main() {
	m := macaron.Classic()
	m.Get("/", func() string {
		return "Hello world!"
	})
	certmagic.Default.Agreed = true
        certmagic.Default.Email = "youremail@gmail.com"
        certmagic.HTTPS([]string{"example.com"}, m)
}
```
