### ISSUE TITLE
How to create a custom Context to test route functions?

### ISSUE THREAD

**Issue by Kheeco** [go-macaron/macaron#151]
If I have a route function like so:

```
func Route(c *macaron.Context) (int, string) {
    value := c.Params("value")
    return 200, "My value is: " + value
}
```

How can I create a custom Context object so I can test the route function? 

Thank you.

**Comment by Unknwon** [comment]
Hi, the proper way to test routes is to use `httptest` package, see http://blog.questionable.services/article/testing-http-handlers-go/.
