### ISSUE TITLE
Read If-None-Match header if ETag is enabled in Static Handler

### ISSUE THREAD

**Issue by thehowl** [go-macaron/macaron#152]
At the moment, the `If-None-Match` header is ignored, whereas it should be checked to be the same as the ETag of the file being served by the static handler. Currently, the static content is always served, even when Macaron should close the connection with a `304 Not Modified` response.

I've added this functionality to [Gitea, in this PR.](https://github.com/go-gitea/gitea/pull/3376/commits/eb161866a794d586418f07e7458ff65d84855af9#diff-e92d900db9a283aeca0ff57133479b66R143) I'd be very glad to port it over to the official macaron repo, if Unknown is available to review & merge the PR :)

**Comment by Unknwon** [comment]
Hi, you can send a PR directly to this repository for review.

**Comment by unknwon** [comment]
A new release is tagged upon resolving this issue: https://github.com/go-macaron/macaron/releases/tag/v1.3.8

Thanks to @humaidq!
