### ISSUE TITLE
func  ctx.JSONString() parser issue.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [go-macaron/macaron#153]
![image](https://user-images.githubusercontent.com/10345361/36825901-e7397c44-1d44-11e8-951c-c77df3fc2bd1.png)

![image](https://user-images.githubusercontent.com/10345361/36825952-35e69f84-1d45-11e8-8cec-7c547d12fd76.png)

![image](https://user-images.githubusercontent.com/10345361/36825958-462066dc-1d45-11e8-94f7-6401730a26bf.png)

I think golang slice with zero element to json should be [], but I got null.

**Comment by Unknwon** [comment]
The zero value of `[]T` is `nil`, it is not the same as an empty slice with zero elements. You need `models := []T{}` to make the slice to be initialized.
