### ISSUE TITLE
Views from multiple directories

### ISSUE THREAD

**Issue by kindlyfire** [go-macaron/macaron#155]
Hello. I wonder if it is possible to render views from multiple directories ?

I tried the following:

```go
m.Use(macaron.Renderer(macaron.RenderOptions{
	Directory: "templates",
	AppendDirectories: []string{
		"templates2",
	},
}))
```

The templates in "templates2" override the templates in "templates" if they exist. Meaning, I cannot add templates to "templates2" without also at least creating a file in "templates" accordingly.

Would it be possible ?

**Comment by Unknwon** [comment]
Hi,

> I wonder if it is possible to render views from multiple directories ?

Your question is very vague, what is "views" and expectation of "multiple directories"?

>Would it be possible ?

What is "it"?
