### ISSUE TITLE
macaron.Static(path, opts) ignores path

### ISSUE THREAD

**Issue by coolaj86** [go-macaron/macaron#158]
Sample Code
===

```go
m.Use(macaron.Static("assets1", macaron.StaticOptions{
  Prefix: "/assets2",
  IndexFile: "index.html",
  FileSystem: myHTTPFileSystem,
}))
```

Expected
=====

A request to `/assets2/foo.html` should try to open the FileSystem as `./assets1/foo.html`

```
curl http://localhost:3000/assets2/
```

Actual
=====

Instead, the FileSystem is opened for "/foo.html"

**Comment by Unknwon** [comment]
I think your implementation of filesystem should aware of the root directory is "assets1" otherwise it is going to just look for "foo.html".

![image](https://user-images.githubusercontent.com/2946214/47478671-3bcdbb80-d7f8-11e8-8807-2a3dcd0b997a.png)

(successful demo with default file system)

**Comment by coolaj86** [comment]
The problem is that `macaron.Static` is calling `myFS.Open("/foo.html")` instead of calling `myFS.Open("/assets1/foo.html")`.

My filesystem never sees `"/assets1"` because `macaron.Static` doesn't send it.

**Comment by Unknwon** [comment]
I think what you're doing is fine, even the default file system is just a wrapper of `http.Dir`:

https://github.com/go-macaron/macaron/blob/9f1e9720ca1c21233db3b230a56e8842bb420ed1/static.go#L75-L91
