### ISSUE TITLE
how can i use index.html call in more then one router?

### ISSUE THREAD

**Issue by merturl** [go-macaron/macaron#160]
i want to call index.html more then one router
but it is not calling
this is my code
package main
```
import (
	"gopkg.in/macaron.v1"
)

func main() {
	m := macaron.Classic()
	m.Use(macaron.Renderer())
	m.Get("/", func(ctx *macaron.Context) {
		ctx.HTML(200, "index")
	})
	m.Get("/dynamic", func(ctx *macaron.Context) {
		ctx.HTML(200, "index")
	})
	m.Run(80)
}
```

and my page result
![image](https://user-images.githubusercontent.com/23473356/48068050-26538b00-e215-11e8-8d03-75762925f7e2.png)
![image](https://user-images.githubusercontent.com/23473356/48068068-2d7a9900-e215-11e8-84cb-2befe3116af9.png)

it is impossible?

**Comment by Unknwon** [comment]
Hi, it is definitely possible and I use this way all the time. Also I tested your code without any problem. Make sure your index.html "really" exists when you called from these two different URLs.
