### ISSUE TITLE
解析time.Time

### ISSUE THREAD

**Issue by shiftwinting** [go-macaron/macaron#164]
type TaskForm struct {
Id int
Name string
Remark string
StartTime time.Time
}

无法获取到 StartTime的值，请教一下要如何获取问题。

**Comment by shiftwinting** [comment]
type TaskForm struct {
	Id               int
	Name             string
	Remark           string
	StartTime        time.Time
}

无法获取到 StartTime的值，请教一下要如何获取问题。

**Comment by Unknwon** [comment]
。。。我不知道你在说什么，请重新整理你的描述

**Comment by shiftwinting** [comment]
不好意思：
是这样：https://github.com/go-macaron/binding/binding.go对应setWithProperType这个函数，目前没有看到解析struct结构体，比如时间time.Time

**Comment by Unknwon** [comment]
暂时不支持直接转，你可以去 ：https://github.com/go-macaron/binding 提一个 feature request，或者取到 string 后自己的路由里转一下。
