### ISSUE TITLE
后端一个api如何持续不断的返回数据给前端

### ISSUE THREAD

**Issue by liujin1993** [go-macaron/macaron#165]
比如前端调用一个api，这个api会执行很长时间，但执行过程中会不断的产生各种数据。
请问如何才能把这些中间数据持续不断的返回给前端，让用户知道执行进度呢？而不是只返回一个最终结果。
第一次遇到这种问题，不知道思路对不对...求指导。

**Comment by Unknwon** [comment]
最土的做法就是后端有个进度记录，前端首次调用完之后就每隔n秒问后端查询进度，然后展示给用户。
