### ISSUE TITLE
不支持go1.11

### ISSUE THREAD

**Issue by corelchen** [go-macaron/macaron#168]
非常喜欢macaron的设计，就是在使用时发现不支持**go1.11.2**。
比如，测试时使用文档中“缓存管理”的示例代码，go1.11.2下运行会报错`[Macaron] PANIC: Value not found for type *macaron.Context`，而在go1.10环境下就可以正常运行。

**Comment by Unknwon** [comment]
我一直用的go1.11.2开发应用，编译发布没有问题。show your code

**Comment by jonsonlion** [comment]
PANIC: Value not found for type *macaron.Context
go 1.11.2
