### ISSUE TITLE
CORS handler?

### ISSUE THREAD

**Issue by tamalsaha** [go-macaron/macaron#169]
Hi,
I have written a CORS handler here: https://github.com/tamalsaha/cors . Are you interested in hosting this under macaron's github org?

Thanks.

**Comment by Unknwon** [comment]
Thanks for asking!

Yes, if you would like to contribute this repository to the "go-macaron" organization, I'll invite you as the member and give you full access to this particular repository.

**Comment by Unknwon** [comment]
Invitation sent. :)

**Comment by tamalsaha** [comment]
Thank you. I joined go-macaron org. Then I tried to transfer my repo but I got this error: `You don’t have the permission to create repositories on go-macaron`

**Comment by Unknwon** [comment]
It's kind of unfamiliar how GitHub manages the repository permission under organization right now... I think you should be able to directly push full history to https://github.com/go-macaron/cors.

**Comment by tamalsaha** [comment]
That worked! Thanks again.
