### ISSUE TITLE
SetURLPrefix有什么用？

### ISSUE THREAD

**Issue by zarte** [go-macaron/macaron#174]
代码如下:
```
m.SetURLPrefix("api")
m.Group("/v1", func() {
		m.Get("/test", func() string  {
			return "test"
		})
	})

```
访问/api/v1/test跟/v1/test一样的，需要的是/v1/test不能访问到。
还有在test里获取到的ctx.Req.URL.Path无论是/api..还是/v1..都是/v1/test没有/api这一层

**Comment by Unknwon** [comment]
就是 trim prefix .. 一般情况下没什么用。。
