### ISSUE TITLE
Automated testing with routes

### ISSUE THREAD

**Issue by jjude** [go-macaron/macaron#179]
I have a problem in automated testing of the application. I think this is not macaron issue. Since I am using macaron, I thought I will ask here.

Here is my directory structure:

```
server
├── go.mod (package app)
├── go.sum
├── main.go (package main)
├── routes
│   ├── register.go (package routes)
├── test
    ├── 00Home_test.go
```

I have a directory named `server` and defined a go module (named app). Routes are registered via `register.go` to which I pass a macaron context. main.go looks like this:

```
m := macaron.Classic()	
routes.Register(m)
m.Run()
```

This works fine. Now I am testing. I'm not able to import the routes and register. Here is my code:

```
package test

m := macaron.Classic()
m.Use(pongo2.Pongoer())
routes.Register(m)

request, _ := http.NewRequest("GET", "/", nil)
response := httptest.NewRecorder()
m.ServeHTTP(response, request)	
```

This fails with `exit status 1`. I have tried with `-v` option, still I don't get any further info why it fails. When I remove the routes (both from import and the register command), the code executes but it is of no use to me.

How to go about testing with routes?

**Comment by unknwon** [comment]
Hi,

```go
request, _ := http.NewRequest("GET", "/", nil)
```

Ignoring error is not a good practice.
