### ISSUE TITLE
如果路由中不存在占位符的话,SetParams会导致panic

### ISSUE THREAD

**Issue by jiangtao92** [go-macaron/macaron#180]
如果路由中不存在占位符的话,SetParams会导致panic
```go
package main

import "gopkg.in/macaron.v1"

func main() {

	m := macaron.Classic()
	m.Get("/", func(ctx *macaron.Context) {
		test := ctx.Params(":test")
		ctx.SetParams(":test", test)
	})

	m.Run()
}
```
https://github.com/go-macaron/macaron/blob/4df59ae8a50bd2e82ed915ff1ce764b1bb128a9d/router.go#L294

不应该直接传入nil, 应该
```go
make(Params)
```

**Comment by unknwon** [comment]
这段代码的本意就是没有发现占位符才能快速匹配：

https://github.com/go-macaron/macaron/blob/4df59ae8a50bd2e82ed915ff1ce764b1bb128a9d/router.go#L291-L296

这个是开发时就应该解决的问题（路由定义和代码不匹配），如果不 panic，我觉得只会把问题隐藏得更深。
