### ISSUE TITLE
PANIC: Value not found for type *macaron.Context

### ISSUE THREAD

**Issue by jonsonlion** [go-macaron/macaron#181]
PANIC: Value not found for type *macaron.Context
go 1.11.2

_Originally posted by @jonsonlion in https://github.com/go-macaron/macaron/issues/168#issuecomment-494438451_

**Comment by ppacher** [comment]
Make sure you used the correct imports. It is **required** to import macaron using `gopkg.in/macaron.v1` if you intend to use any of the middlewares provided. If you import using `github.com/go-macaron/macaron` it will be a different package.

@Unknwon did you consider supporting github imports with go-modules? It should actually make gopkg.in obsolete.

**Comment by Unknwon** [comment]
@ppacher Has given the cause and solution.

Thanks for the suggestion! But even start using Go modules, the import path will not be change in my opinion, because everywhere will have to change.
