### ISSUE TITLE
Infinite redirect with Prefix in StaticOptions

### ISSUE THREAD

**Issue by mattdavis90** [go-macaron/macaron#201]
It looks as though #199 introduced a bug causing an infinite redirect when using `StaticOptions.Prefix`. This issue is around `path.Clean` and passing in `ctx.req.URL.Path`. I think this should be checked against `opt.Prefix` rather than "/" but this requires a special case when `opt.Prefix == ""` which is the fault.

Minimal example:
```go
package main

import (
        "gopkg.in/macaron.v1"
        "net/http"
)

func main() {
        m := macaron.New()
        m.Use(macaron.Static("public", macaron.StaticOptions{
                Prefix: "/public",
        }))
        srv := &http.Server{
                Addr:    "0.0.0.0:8000",
                Handler: m,
        }
        srv.ListenAndServe()
}
```
Put an `index.html` in the `public` directory and navigate to `http://127.0.0.1:8000/public` you should get served the index.html but instead will get an infinite redirect to `/public/`.

**Comment by mattdavis90** [comment]
I think changing line 153 in `static.go` to the following works.

```go
if !strings.HasSuffix(redirPath, opt.Prefix) {
```

**Comment by humaidq** [comment]
> I think changing line 153 in `static.go` to the following works.
> 
> ```go
> if !strings.HasSuffix(redirPath, opt.Prefix) {
> ```

This breaks other tests, I have tried other variations with similar results.
