### ISSUE TITLE
能否增加logrus

### ISSUE THREAD

**Issue by ihuanglei** [go-macaron/macaron#207]
@unknwon

**Comment by unknwon** [comment]
Hi, you can make a logrus object yourself and inject it using `m.Map`: 

https://github.com/go-macaron/macaron/blob/d229aed598800fac0be5261b1b14e4bf9b4e6333/macaron.go#L131

Then use it like this:

https://github.com/go-macaron/macaron/blob/d229aed598800fac0be5261b1b14e4bf9b4e6333/logger.go#L45-L73
