### ISSUE TITLE
middleware for fis

### ISSUE THREAD

**Issue by transtone** [go-macaron/macaron#39]
https://github.com/fex-team/fis 是来自百度的前端框架工具，已经有朋友把它做成了matini的中间件，其用法示例在：https://github.com/xiangshouding/martini-fis-app 。

当时看到这个工具时一时兴起就在群里提了一下，仔细看了用法示例，又在想这种修改模板引擎，植入前端框架的功能的做法是不是有些偏门，原matini集成项目貌似好久都没有维护更新过了。我个人还是喜欢前后端完全分离，这样更合乎软件的正交。

很喜欢百度的一些前端工具，如fis/echarts，如果能够更好的和macaron结合自然是很美好的事。烦请无闻老师帮忙分析一下利弊：有没有必要做这么一个中间件，其优势在哪。

**Comment by Unknwon** [comment]
您好，我看了一下这个fis，更像个前端发布解决方案，而且20天前还发布了个dev版本。应该还算是活跃的项目，我觉得可以集成下，但因为我本身不用，可能不能很好的测试了。:smiley:

**Comment by transtone** [comment]
原martini集成是通过修改模板渲染来集成的，但这样一来就没法自由选择渲染模板了（我个人比较钟情pongo2）。您看有什么好的集成方法可以单独出来所有模板库都能用的。测试方面目前可以交给我。

**Comment by Unknwon** [comment]
感觉有点懂你的意思了~

**Comment by Unknwon** [comment]
今天看到一个知乎的贴子将前端也提到了fis，看来这个中间件还是会蛮有意思的
