### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by mephux** [go-macaron/macaron#40]
I love macaron but the docs/getting started needs a little help. I learned and got started mostly from reading the gogs source code. What do you think about adding generators like ruby on rails does to help people get started? I think this would be a great differentiator as well for the project.

`macaron new todo`

```
todo/
   models/
   lib/
   views/
   routers/
   todo.go
```

`macaron gen route users`

```
 todo/
   models/user.go
   routers/user.go
   views/user/*.html
```

etc.

**Comment by mephux** [comment]
to clarify.. the docs are pretty good and have improved a lot. I'm mostly talking about structure and code organization.. and making production apps with macaron.

**Comment by Unknwon** [comment]
Glad you like macaron!

This idea is very interesting and I've been think it for a while too, but just what are the features can this generator provide. Heard  ROR many times but I don't use ruby.

**Comment by mephux** [comment]
@Unknwon This would mostly be for convenience and getting started quickly with macaron as a framework.

The generators should be pretty opinionated and structure a blank project for development. http://guides.rubyonrails.org/generators.html

**Comment by Unknwon** [comment]
Thanks for the tip!

**Comment by mephux** [comment]
@Unknwon i'm offering to help build it as well - just want your thoughts on first steps and how you would like it implemented.

Should just package a macaron binary with the framework for bootstrapping and project creation. Let me know.

**Comment by Unknwon** [comment]
Sure, so the first step is to define

- what are things we want to generator do?
- which config format should we use?

**Comment by mephux** [comment]
@Unknwon roger. Here are my thoughts.

1. I would make one for basic CRUD actions and project struct to begin with. Example

`macaron new todo-app --middleware=csrf,session,binpack`

```
  todo-app/
   models/
   routes/
   views/
   todo-app.go
   .........
```

This should include the requested imports for the middleware listed on the cli.

or

`macaron add user "name:string,email:string,salt:string,hash:string"`

```
  todo-app/
   models/
     user.go
   views/
     user/
        edit.html
        delete.html
        create.html
        view.html
        users.html
   router/
    user/
     user.go
```

The model, router and views would contain boilerplate code using xorm etc.

# model
```go
package models

type User struct {
  Id int64
  Name string `xorm:""`
  Email string `xorm:""`
  Salt string `xorm:""`
  Hash string `xorm:""`
}
```

# router

```go
const (
	USERS       base.TplName = "users/list"
	USERS_CREATE base.TplName = "users/create"
	USERS_VIEW   base.TplName = "users/view"
	USERS_DELETE base.TplName = "users/delete"
	USERS_EDIT   base.TplName = "users/edit"
)

func Users(ctx *middleware.Context) {}
func Create(ctx *middleware.Context) {}
func CreatePost(ctx *middleware.Context) {}
func Edit(ctx *middleware.Context) {}
func EditPost(ctx *middleware.Context) {}
func View(ctx *middleware.Context) {}
func Delete(ctx *middleware.Context) {}
func DeletePost(ctx *middleware.Context) {}
```

```go
	m.Group("/users", func() {
		m.Get("/", user.Users)

		m.Group("/:id", func() {
			m.Get("", user.View)
			m.Get("/edit", collection.EditView)
			m.Post("/edit", collection.Edit)
			m.Get("/delete", collection.DeleteView)
			m.Post("/delete", collection.Delete)
		})
	}, reqSignIn)
```

2. We could just use go templates to build the expected layout.

**Comment by mephux** [comment]
@Unknwon for us it would mostly be picking the conventions that made the most sense and how/what we wanted to support for the first cut of this.. simple would be best.

**Comment by mephux** [comment]
@Unknwon looks like beego went this same path http://beego.me/docs/install/bee.md

**Comment by Unknwon** [comment]
@mephux very helpful examples!

So there is a thing I was straggling: should generator only cares about to create process? What if user modified some content but need generator to add, let's say, another middleware. What should happen to the content that user is modified?

**Comment by mephux** [comment]
@Unknwon I know - I was at your golang talk here in Boston. 

So, my thoughts on that would be to prompt them (user.of was modified already - are you sure you want to replace it? [y/N]). or split up the code into different files.

Is it possible to split the router parts.. i.e https://github.com/gogits/gogs/blob/master/cmd/web.go#L168-L341 into different files? - The more split up the source is there easier it will be to control this process.

**Comment by Unknwon** [comment]
> I know - I was at your golang talk here in Boston.

Oops, did not notice :stuck_out_tongue_closed_eyes:

> So, my thoughts on that would be to prompt them (user.of was modified already - are you sure you want to replace it? [y/N]). or split up the code into different files.

Looks good!

> Is it possible to split the router parts.. i.e https://github.com/gogits/gogs/blob/master/cmd/web.go#L168-L341 into different files? - The more split up the source is there easier it will be to control this process.

Yes, as long as process is not concurrency, and pass the `m` instance to corresponding place, like `routers.InitRoutes(m)`

**Comment by mephux** [comment]
Ok, sounds good to me. Do you have any thoughts on how you would want a brand new macaron app to be structured? If we can decide on one i'll start on a prototype.

Maybe?

```
my-app/
  lib/
    middleware/
  models/
  views/
  controllers/
  routers/
  config/
    app.ini
  scripts/
    // we could add helpful scripts for running the app
    // or maybe include a default makefile?
  my-app.go
```

**Comment by Unknwon** [comment]
First of all, we need to decide **what name to call this generator**, and **where to put its source code**.

Then I would prefer to use `github.com/codegangsta/cli` instead of parse everything ourselves.

For the default app structure, I personally like:

```
my-app/
  conf/
    app.ini
  modules/
    middleware/
    base/
    setting/
  models/
  templates/
  public/
    public/js
    public/css
    public/img
  routers/
  scripts/
  my-app.go
```

But I think generator should be able to optionally take an .yml as config file as well.

**Comment by mephux** [comment]
cool, sounds good.

Calling it `macaron` makes sense to me  - and having it ship with the main macaron code would be nice imho.

then people can just do `go get github.com/Unknwon/macaron/...`

`macaron new app`

and be up and running in seconds.

What are you thoughts on godep? Would it make sense to use godep to add the middleware if the user askes for it.. so they can then just do.. `make` and have a working project.

This is my standard makefile https://github.com/mephux/rmslack/blob/master/Makefile#L21-L38 - how do you go about dep tracking?

**Comment by Unknwon** [comment]
> Calling it macaron makes sense to me - and having it ship with the main macaron code would be nice imho.

Put it under `github.com/Unknwon/macaron/macaron` would be my thought, too.

> What are you thoughts on godep? Would it make sense to use godep to add the middleware if the user askes for it.. so they can then just do.. make and have a working project.

I personally does not feel good about it, 'cause it saves duplicated copies in to git repository(non-git repository is fine). But in case needed, I think simple wrapper around it should be good? Like `macaron run` can execute `godep go build` and then run the binary.

**Comment by mephux** [comment]
Ok, sounds good to me.

**Comment by Unknwon** [comment]
BTW, is using toml better than yml? Or, let's see how's going with yaml and see if change to toml is needed?

**Comment by Unknwon** [comment]
Also, should I create basic files in main macaron repo before you fork?

**Comment by Unknwon** [comment]
I have strong OCD so...

**Comment by mephux** [comment]
toml would be my pick.. up to you tho. I forked and started already. didn't do a lot tho. https://github.com/mephux/macaron/tree/master/macaron

**Comment by mephux** [comment]
I added you to the repo as well.

**Comment by Unknwon** [comment]
I saw it. I'll push some basic design changes soon!

**Comment by mephux** [comment]
awesome, thank you! I think this will be an awesome add to the project and help get new people into the framework.

**Comment by Unknwon** [comment]
True! I suffer a lot myself for starting new macaron projects.

**Comment by mephux** [comment]
@Unknwon lol, same here.. I was going to build it anyway but figured I would contrib back and make sure it aligned properly with what you wanted.

**Comment by mephux** [comment]
@Unknwon do you have a chatroom setup for macaron? I wanted to talk out this concept https://github.com/mephux/macaron/blob/master/macaron/templates/new/config.toml for bootstrapping a new project..

The concept is.. if you want to override from the CLI you can.. but if you want to load your own config.. you just need to offer the same settings.

**Comment by Unknwon** [comment]
Gitter sucks me for a while but finally https://gitter.im/Unknwon/macaron

**Comment by gedw99** [comment]
any news on this ?
Is a good idea for large applications that need lots of data plumbing

**Comment by Unknwon** [comment]
> Is a good idea for large applications that need lots of data plumbing

Not sure what do you exactly mean?

**Comment by mephux** [comment]
@Unknwon They just mean a lot of boilerplate (non-unique - could be auto generated) code is needed to get started. is that correct @gedw99 ?

**Comment by gedw99** [comment]
Yep you nailed it

**Comment by Unknwon** [comment]
I see... hmm. Thanks

**Comment by unknwon** [comment]
Close as won't implement.
