### ISSUE TITLE
能否增加SSE支持

### ISSUE THREAD

**Issue by cgyy** [go-macaron/macaron#53]
类似于这样的
https://github.com/gin-gonic/gin/tree/master/examples/realtime-chat
https://github.com/gin-gonic/gin/issues/285

**Comment by Unknwon** [comment]
看起来是个不错的功能！已加到todo。。

**Comment by flixgithub** [comment]
我这儿也有这个需求,如果有需要我可以帮忙做一下的

**Comment by unknwon** [comment]
@flixgithub 最完美的情况就是搞个中间件，比如 go-macaron/sse 这样的，你怎么看？

**Comment by unknwon** [comment]
Closing, please see https://github.com/flamego/flamego/issues/85.
