### ISSUE TITLE
Router matching priority

### ISSUE THREAD

**Issue by ipfans** [go-macaron/macaron#60]
As document mentions:

```
Matching priority of same pattern is first add first match.
```

But in this case:

```
/user/:uid/:name1/:name2/hit
/user/:uid/:name1/hit
```

and first router will never hit.

if change Placeholders to regex also not working:

```
/user/:uid/:name1/([0-9]+)/hit
/user/:uid/:name1/hit
```

**Comment by Unknwon** [comment]
Yes, but you should read next line as well:

> More detailed pattern gets higher matching priority:

**Comment by Unknwon** [comment]
To hit first one (`/user/:uid/:name1/:name2/hit`):

```
/user/12/hello/world/hit
```

**Comment by Unknwon** [comment]
Maybe is just because my English wording is bad, I shall say `more levels gets higher priority`?

**Comment by ipfans** [comment]
ok, it seems that I have mistake.

**Comment by Unknwon** [comment]
No problem :trollface:
