### ISSUE TITLE
路由通配符不支持下划线

### ISSUE THREAD

**Issue by cgyy** [go-macaron/macaron#61]
```go
m.Get("/:id/images/:image_id/edit", (*ProductsController).EditImages)
```
以上代码会报404错误，只有把image_id 改成imageid 才可以

建议： tree.go第48行
```go
var wildcardPattern = regexp.MustCompile(`:[a-zA-Z0-9]+`)
// 可不可以改成regexp.MustCompile(`:[a-zA-Z0-9_]+`)
```

**Comment by Unknwon** [comment]
按照你的写法改了之后。。。:cms_:id 就悲剧了。。

**Comment by cgyy** [comment]
:cms_:id 是两个冒号，按说不匹配这个正则才对啊。我觉得一般编程语言中的变量都允许字母、数字和下划线。所以这个也支持下划线比较自然

**Comment by Unknwon** [comment]
> :cms_:id 是两个冒号，按说不匹配这个正则才对啊

设计就是这样的，一个冒号只是一个特殊形式。。

**Comment by cgyy** [comment]
@Unknwon 
不好意思，是我的文档看的不够仔细，但是还是不太明白这种用法:
http://go-macaron.com/docs/middlewares/routing

```go
m.Get("/cms_:id([0-9]+).html", func(ctx *macaron.Context) string {
    return fmt.Sprintf("The ID is %s", ctx.Params(":id"))
})
```

**Comment by Unknwon** [comment]
额。。我例子举措了。。sorry。。看测试用例。。https://github.com/go-macaron/macaron/blob/v1/tree_test.go#L34-L36

**Comment by cgyy** [comment]
@Unknwon 明白了，谢谢:D

**Comment by Unknwon** [comment]
:trollface:
