### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by onlyjob** [go-macaron/macaron#64]
README says "Current version: 0.8.0" but there are no tags...
Formal releases are useful for downstream maintainers.
Please consider tagging.

**Comment by Unknwon** [comment]
I will tag once reach 1.0 :D

**Comment by Unknwon** [comment]
BTW, this package support to use `gopkg.in/macaron.v1`.

**Comment by onlyjob** [comment]
Thanks, I'm looking forward to see first tagged release.
Unfortunately `gopkg.in/macaron.v1` is not a substitute for tagged releases. Tags are useful for monitoring, package dependencies, exporting tarballs, etc.

**Comment by Unknwon** [comment]
:smiley:

**Comment by Unknwon** [comment]
Done!
