### ISSUE TITLE
FTBFS: undefined: ini.Empty

### ISSUE THREAD

**Issue by onlyjob** [go-macaron/macaron#67]
with Go 1.5 I'm getting FTBFS:

    macaron.go:275: undefined: ini.Empty

**Comment by Unknwon** [comment]
Hi, please do `go get -u` to force update all deps.

**Comment by onlyjob** [comment]
I see, this is because I use [released version](https://github.com/go-ini/ini/releases) of _go-ini_ while Macaron requires unreleased snapshot of the latter. FYI latest snapshot of _go-ini_ is affected by test failures. Please consider depending on tagged releases whenever possible.

**Comment by Unknwon** [comment]
>  FYI latest snapshot of go-ini is affected by test failures

Please give prove your words. http://gocover.io/github.com/go-ini/ini

 > I see, this is because I use released version of go-ini while Macaron requires unreleased snapshot of the latter.

Manually interchange dep version to lower one gets no grantees it will compile.

**Comment by onlyjob** [comment]
Well, this is what I get when I build latest go-ini:

~~~~
...
    Get key strings ✘✔✔ 
    Delete a key ✔✔✔ 
    Has Key ✘✔✔✔✔ 
    Has Value ✘✔✔✔ 
    Get section strings ✔✔✔ 
    Delete a section ✔✔✔ 
    Create new sections ✔✔ 
 
Failures: 
  * /mnt/tmpssd/src/PKG-GO/golang-gopkg-ini.v1/ini-03e0e7d51a13a91c765d8d0161246bc14a38001a/_build/src/gopkg.in/ini.v1/ini_test.go  
  Line 387: 
  Expected: 'STRING,BOOL,BOOL_FALSE,FLOAT64,INT,TIME,DURATION,UINT' 
  Actual:   'STRING,BOOL,BOOL_FALSE,FLOAT64,INT,TIME,DURATION,UINT,STRING_404,BOOL_404,FLOAT64_404,INT_404,UINT_404,TIME_404,DURATION_404,INT64_404' 
  (Should be equal) 

  * /mnt/tmpssd/src/PKG-GO/golang-gopkg-ini.v1/ini-03e0e7d51a13a91c765d8d0161246bc14a38001a/_build/src/gopkg.in/ini.v1/ini_test.go  
  Line 401: 
  Expected: true 
  Actual:   false 

  * /mnt/tmpssd/src/PKG-GO/golang-gopkg-ini.v1/ini-03e0e7d51a13a91c765d8d0161246bc14a38001a/_build/src/gopkg.in/ini.v1/ini_test.go  
  Line 410: 
  Expected: true 
  Actual:   false 
~~~~

All tests from tagged _v0_ are passing.

> Manually interchange dep version to lower one gets no grantees it will compile.

But that's the reality of downstream package maintenance. We have to reuse packages and we try to use stable releases whenever possible. You might find it interesting to read about [software versioning](https://en.wikipedia.org/wiki/Software_versioning). Also I hope that some information from [Debian UpstreamGuide](https://wiki.debian.org/UpstreamGuide) will be useful.

**Comment by Unknwon** [comment]
Thanks your report!

Which system are using test against?

**Comment by onlyjob** [comment]
Debian "testing" and "unstable" on _amd64_ and _i686_.

**Comment by Unknwon** [comment]
Hmm... Interesting... I'll do a test on my vagrant Ubuntu amd64 and i386 see how it goes.

**Comment by onlyjob** [comment]
Thanks. :)

**Comment by Unknwon** [comment]
@onlyjob FYI, tests passed on my wheezy-amd64 vagrant. So I'm not sure why it is failing on your side.
