### ISSUE TITLE
URL validation is too strict

### ISSUE THREAD

**Issue by angus-g** [go-macaron/macaron#69]
A URL such as "http://localhost:8888" is rejected by the `Url` validator, but I think it should be accepted

**Comment by Unknwon** [comment]
If you know regexp really well, you can help me https://github.com/go-macaron/binding/blob/master/binding.go#L249 :trollface:

**Comment by angus-g** [comment]
I haven't thought carefully about it, but maybe a naive way would be to make the "dot part" use `*` instead of `+`:

    urlPattern = regexp.MustCompile(`(http|https):\/\/[\w\-_]+(\.[\w\-_]+)*([\w\-\.,@?^=%&amp;:/~\+#]*[\w\-\@?^=%&amp;/~\+#])?`)
                                                                          ^

**Comment by NiklasRosenstein** [comment]
I think what @angus-g proposes is reasonable. The name "localhost" is just a convention, but any name with or without periods would be valid.
