### ISSUE TITLE
Can I have the benchmark test result of Macaron library?

### ISSUE THREAD

**Issue by leonli** [go-macaron/macaron#71]
As what I mentioned in title, put a benchmark sample & code in the project would be much appreciate.
I really would like to know how Macaron solved the problem against to Martini.

**Comment by Unknwon** [comment]
OK, I'll run my fork of benchmark again and post them.

**Comment by leonli** [comment]
+1

**Comment by Unknwon** [comment]
Done by https://github.com/Unknwon/go-http-routing-benchmark
