### ISSUE TITLE
logo有bug

### ISSUE THREAD

**Issue by leonli** [go-macaron/macaron#72]
古语云“画龙点精”，LOGO是一头盲龙，@insionng 同学把龙的神韵（眼睛）弄哪里去了？

PS: 原图是有眼睛的哦.

**Comment by Unknwon** [comment]
应该是作者后来改版了，我看了 PSD 里也没眼睛。。。

**Comment by leonli** [comment]
不对啊，这里有眼睛
http://xtremeyamazaki.deviantart.com/art/Tribal-Dragon-27005087
让@insionng君加上嘛，画龙点精...

**Comment by Unknwon** [comment]
我说作者后来改版了。。

**Comment by leonli** [comment]
好吧.

**Comment by Unknwon** [comment]
:trollface:

**Comment by insionng** [comment]
@leonli 嗯，那是后来改了~

**Comment by Unknwon** [comment]
@insionng 卧槽。多少年了，你又出现了
