### ISSUE TITLE
使用binding，无限panic.

### ISSUE THREAD

**Issue by cyuxlif** [go-macaron/macaron#75]
![1](https://cloud.githubusercontent.com/assets/5780053/12315622/11b15e34-bab8-11e5-9d10-cf163bb00954.png)
![2](https://cloud.githubusercontent.com/assets/5780053/12315625/1517197e-bab8-11e5-8931-c8affc2f75c8.png)
![3](https://cloud.githubusercontent.com/assets/5780053/12315627/173a34ca-bab8-11e5-8f48-7f5e52ae487a.png)

**Comment by Unknwon** [comment]
截图看下你的导入包部分

**Comment by cyuxlif** [comment]
![4](https://cloud.githubusercontent.com/assets/5780053/12317439/47006198-bacc-11e5-8ba8-49e9c435fc90.png)

不知道什么原因。 一般碰到这种panic我该怎么定位问题，求指教

**Comment by Unknwon** [comment]
因为文档说了。。

> import "gopkg.in/macaron.v1"

**Comment by cyuxlif** [comment]
![5](https://cloud.githubusercontent.com/assets/5780053/12317577/6335075a-bacd-11e5-9a64-0da56658bcab.png)
![6](https://cloud.githubusercontent.com/assets/5780053/12317586/72aceb8a-bacd-11e5-8960-43708538afd0.png)

换成 这个还是一样

**Comment by cyuxlif** [comment]
![6](https://cloud.githubusercontent.com/assets/5780053/12317595/8807bdac-bacd-11e5-9015-88d2562b20fc.png)

**Comment by Unknwon** [comment]
一样是指。。？

**Comment by cyuxlif** [comment]
![7](https://cloud.githubusercontent.com/assets/5780053/12317607/afe71ae8-bacd-11e5-8e71-ae6a6d363a7b.png)

**Comment by Unknwon** [comment]
你确定重新构建再运行了吗？

**Comment by cyuxlif** [comment]
package main

import (
	"html/template"
	"gopkg.in/macaron.v1"
	//"github.com/go-macaron/macaron"
	zd_template "zhaodi/modules/template"
	"zhaodi/modules/middleware"
	"zhaodi/routers"
	//"zhaodi/routers/user"
	"github.com/go-macaron/binding"
	//"zhaodi/modules/auth"
	_ "zhaodi/modules/setting"
	_ "zhaodi/models"
	"fmt"
)



//var funcMap = map[string]interface{}{
//	"str2html": base.Str2html,
//}

func newZhaodi() *macaron.Macaron {
	m := macaron.Classic()
	// Middlewares.
	m.Use(macaron.Renderer(macaron.RenderOptions{
		Funcs: []template.FuncMap{zd_template.Funcs},
	}))
	m.Use(middleware.Contexter())

	return m
}

type ContactForm struct {
	Name           string `form:"name" binding:"Required"`
	Email          string `form:"email"`
	Message        string `form:"message" binding:"Required"`
	MailingAddress string `form:"mailing_address"`
}


func main() {
	m := newZhaodi()

	//bindIgnErr := binding.BindIgnErr
	//bind = binding.Bind

	// Routers.
	m.Get("/", routers.Home)
	m.Post("/upload", routers.Upload)
	m.Get("/addAss", routers.AddAss)
	m.Get("/ass", routers.Ass)
	//m.Get("/getass", routers.GetAss)


	m.Get("/contact/submit", func(contact ContactForm) string {
			return "xxxxxxxxxxx"
		})
	m.Post("/contact/submit", binding.Bind(ContactForm{}),func(ctx *macaron.Context, contact ContactForm) string {
			contact = ContactForm{Name:"ssss"}
			fmt.Println(ctx.Query("name"))
			//return ctx.Query("name")
			return fmt.Sprintf("Name: %s\nEmail: %s\nMessage: %s\nMailing Address: %v",
				contact.Name, contact.Email, contact.Message, contact.MailingAddress)
		})



//	m.Group("/user", func() {
//			m.Get("/subject/add", user.SubjectAddView)
//			m.Post("/subject/add",user.SubjectAddSave)
////			m.Post("/subject/add", binding.Bind(auth.CreateSubjectForm{}), func(form auth.CreateSubjectForm) string{
////					fmt.Println(form)
////					return fmt.Sprintf("Name: %n\nEmail: %s\nMessage: %s\nMailing Address: %v",
////						form.Type, form.Title, form.Alias)
////				})
//			m.Get("/episode/add", user.EpisodeAddView)
//			m.Post("/episode/add", user.EpisodeAddSave)
//		})
	m.Run()
    
    //
}



main包的代码

**Comment by cyuxlif** [comment]
是的， 每次都 ctrl+c 重新 bra run的

**Comment by Unknwon** [comment]
贴得代码确实有点不太能看懂。。能不能格式一下。。

**Comment by cyuxlif** [comment]
![8](https://cloud.githubusercontent.com/assets/5780053/12317734/dfc82bde-bace-11e5-994b-d19e19f902a0.png)
![9](https://cloud.githubusercontent.com/assets/5780053/12317737/e795cc90-bace-11e5-9087-e0b094e0ebc0.png)

**Comment by cyuxlif** [comment]
红色是因为 idea 不能识别 文件夹名和包名不同造成的。 程序编译是正常的

**Comment by Unknwon** [comment]
你的 macaron 包是放在 `$GOPATH/src/gopkg.in/macaron.v1` 目录吧？

**Comment by cyuxlif** [comment]
是的
![10](https://cloud.githubusercontent.com/assets/5780053/12317800/745816f6-bacf-11e5-952a-1362b3936b8f.png)

**Comment by Unknwon** [comment]
不用binding，比如跑个 hello world 正常吗？

**Comment by cyuxlif** [comment]
![11](https://cloud.githubusercontent.com/assets/5780053/12317849/f521a518-bacf-11e5-8ec8-780a837195b7.png)

**Comment by Unknwon** [comment]
比如这个例子：https://go-macaron.com/docs/intro/getting_started#%E6%89%A9%E5%B1%95%E7%A4%BA%E4%BE%8B

**Comment by cyuxlif** [comment]
正常的， 模板都可以输出的

	m.Get("/contact/submit", func() string {
			return "xxxxxxxxxxx"
		})
这个也会正常输出

**Comment by Unknwon** [comment]
扩展示例是正常的对吧？

**Comment by cyuxlif** [comment]
![13](https://cloud.githubusercontent.com/assets/5780053/12318036/db72bf10-bad1-11e5-8cc6-8283df67bc26.png)

![14](https://cloud.githubusercontent.com/assets/5780053/12318041/e12c2108-bad1-11e5-8da8-ef34de10a031.png)


![12](https://cloud.githubusercontent.com/assets/5780053/12317999/a12bdb70-bad1-11e5-861c-70ee76e63041.png)

使用 gopkg.in/macaron.v1后， hello word也不输出了，

**Comment by cyuxlif** [comment]
![16](https://cloud.githubusercontent.com/assets/5780053/12318094/7f911074-bad2-11e5-8dd2-e4aab66e7b19.png)
![15](https://cloud.githubusercontent.com/assets/5780053/12318095/8499ff90-bad2-11e5-9c4b-39343e6c1964.png)

全部换成 gopkg.in/macaron.v1后 好了。。。

**Comment by cyuxlif** [comment]
我选择github.com/go-macaron/macaron主要是因为， idea不识别gopkg.in/macaron.v1这个。
看来还是得选择稳定版本。。。

**Comment by Unknwon** [comment]
额。。主要是因为macaron用到反射，是根本包来决定的，不同包就是不同类型，所以会提示找不到。。

**Comment by cyuxlif** [comment]
恩 多谢了，我觉得macaron方便实用， macaron有没有交流群之类的 我可以加下。

**Comment by Unknwon** [comment]
有的~ 371440803 欢迎
