### ISSUE TITLE
host设置和电脑不同

### ISSUE THREAD

**Issue by proudlily** [go-macaron/macaron#76]
我的电脑的ip是：192.168.1.116
运行 
```golang
m.run()
```
终端显示：
```
[Macaron] listening on linux-hiad:4000 (development)
[Macaron] listen tcp: lookup linux-hiad on 192.168.1.1:53: no such host
exit status 1

```

**Comment by Unknwon** [comment]
如果值调用了 `m.Run()`，监听的是 `0.0.0.0`。

**Comment by cgyy** [comment]
@proudlily 是不是电脑连接的WiFi？

**Comment by proudlily** [comment]
@cgyy 没有呀，连接的网线。是程序在解析linux-hiad 的dns么？（linux-hiad是我的电脑

**Comment by cgyy** [comment]
@proudlily 你在终端下运行 echo $PORT 看看打印出来的是什么？
怀疑你安装的其他程序设置了这个环境变量

**Comment by Unknwon** [comment]
@cgyy 说得有道理。。

**Comment by proudlily** [comment]
@cgyy 在终端输入
`echo $PORT`
终端是空的（没有任何结果）

**Comment by cgyy** [comment]
@proudlily 那试试在m.run() 前面增加一行 fmt.Println(os.Getenv("PORT"))
看看能打印出什么东西来？

**Comment by proudlily** [comment]
@cgyy 打出的是
```
[Macaron] listening on linux-hiad:4000 (development)
[Macaron] listen tcp: lookup linux-hiad on 192.168.1.1:53: no such host
exit status 1
```
多了一个空行，（
``
 It returns the value, which will be empty if the variable is not present.
``
）

**Comment by Unknwon** [comment]
这个 issue 有进展吗。。？

**Comment by proudlily** [comment]
@Unknwon 0.0不知道怎么解决？不知道问题在哪里？

**Comment by Unknwon** [comment]
换台电脑也是这个问题》

**Comment by proudlily** [comment]
换台电脑？我只有一台电脑啊。0.0

**Comment by Unknwon** [comment]
你用 `m.Run("0.0.0.0:4000")`呢？

**Comment by proudlily** [comment]
`m.Run("0.0.0.0", 4000)`
这样子可以。。。。谢谢=w=

**Comment by Unknwon** [comment]
恩。那就行。。默认取环境变量你的shell 环境可能有未知的自动设置导致坑爹。。
