### ISSUE TITLE
官方网站速度很慢

### ISSUE THREAD

**Issue by myml** [go-macaron/macaron#77]
每天首次打开网页1.8分钟...
因为上面有文档,查的时候不太方便

**Comment by Unknwon** [comment]
服务器在加拿大。。爱莫能助啊 0 0

**Comment by myml** [comment]
嗯嗯，这个明白。不过比较耗时的是semantic这个前端库，建议使用
http://cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.css
http://cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.js
之类的CDN来加速，另外其他资源的加载速度都很快，可见也不一定全是网络原因

**Comment by Unknwon** [comment]
好吧。。这个还是可以解决的，我研究下

**Comment by myml** [comment]
睡的好晚。。。这个其实也不是很重要的事

**Comment by Unknwon** [comment]
。。。没事，我们不在一个时区。。

**Comment by myml** [comment]
哇

**Comment by Unknwon** [comment]
测试了下。。你是不是搞错了什么。。这两个文件都是直接从服务器拉取的。。不是 CDN。。

**Comment by myml** [comment]
没懂,我是直接百度的semantic CDN 公共库,我这边ping 地址也是离我比较近的的地点,这个不就是CDN吗?
可能是因为这个是Bootstrap中文网做的,只对国内用户有效,你那边直接从源主机获取了...好麻烦

**Comment by myml** [comment]
对了,我直接把文档clone下来就行了

**Comment by Unknwon** [comment]
官网的 Semantic 根本不是从 CDN 拉取的。。所以我不知道你在说啥。。

**Comment by myml** [comment]
今天用Opera打开Macaron网站，发现是google字体的问题。。。
