### ISSUE TITLE
Context怎么不渲染输出html文件

### ISSUE THREAD

**Issue by myml** [go-macaron/macaron#78]
用ctx.ServeFileContent不被浏览器解析html,难道要每个页面自己添加Head?
用ctx.Html异常提示没有注册模板引擎,但是我的html并不需要进行渲染,如果是更改模板语法分隔符,会不会影响效率,,这个时候有没有简单的方法呢?

**Comment by Unknwon** [comment]
你用调用的方法是用来输出纯文本内容的。。别乱用啊大哥 https://gowalker.org/gopkg.in/macaron.v1#Context_ServeFileContent

**Comment by myml** [comment]
恩,这个试过了,我现在用的方法是第二种方法更改模板分隔符{{}}

**Comment by myml** [comment]
但是想着有没有更简单的方法能直接返回html文件,比如ctx.Html在没有模板的情况下能够直接输出html文件

**Comment by Unknwon** [comment]
改 Header。。。或者自己实现内存版的文件操作，也可以骗过 ctx.HTML

**Comment by myml** [comment]
..还是改分隔符容易些

**Comment by Unknwon** [comment]
:joy: 哈哈 你用Go 自带的模板改分隔符就没什么效率问题

**Comment by myml** [comment]
go的标准模版效率很高?

**Comment by Unknwon** [comment]
我不知道你在说什么。。。

**Comment by myml** [comment]
...睡觉,都是小事

**Comment by Unknwon** [comment]
:trollface:
