### ISSUE TITLE
ctx.JSON报错

### ISSUE THREAD

**Issue by myml** [go-macaron/macaron#79]
package main
import "gopkg.in/macaron.v1"
func main() {  
	m := macaron.Classic()
	type Person struct {
		Name string
		Age  int
		Sex  string
	}
	m.Get("/json", func(ctx *macaron.Context) {
		p := Person{"Unknwon", 21, "male"}
		ctx.JSON(200, &p)
	})
	m.Run()
}
最为简单的代码,这个是文档上的例子,一直报错
runtime error: invalid memory address or nil pointer dereference

**Comment by Unknwon** [comment]
你确定这是文档给你的例子？哪里？

**Comment by myml** [comment]
在模板的教程里有讲怎么输出json，这个和教程的类似

**Comment by myml** [comment]
应该怎么输出json呢，不管加不加&都是报错

**Comment by Unknwon** [comment]
没说吗。。https://go-macaron.com/docs/middlewares/templating

**Comment by myml** [comment]
明白了，JSON函数是依赖模板～好奇怪的用法～～

**Comment by Unknwon** [comment]
不奇怪上不了珠穆朗玛峰！😂

**Comment by myml** [comment]
不过也挺有趣的，之前看模板设置里面有个序列化json是否用缩进，觉的挺奇怪的，原来是这样用的，谢了(^～^)
