### ISSUE TITLE
sockets中间件注册后，影响正常路由

### ISSUE THREAD

**Issue by myml** [go-macaron/macaron#80]
`

	m := macaron.Classic()
	m.Use(sockets.Messages())
        type Message struct {
	Id   int
	Name string
        }
	m.Use(sockets.JSON(Message{}))
	m.Get("/a", func() {
		log.Println("hello")
	})
	m.Run()
`
访问http://127.0.0.1:4000/a 提示Origin not allowed，是哪里的错呢？

**Comment by Unknwon** [comment]
因为必须是本站自己发出的请求吧

**Comment by myml** [comment]
可是我访问的并不是ws地址，而是普通的get路由，这样被跨域拦截的话，我又怎么才能提供html页面给浏览器呢

**Comment by Unknwon** [comment]
别全局拦截啊。。用组路由 https://go-macaron.com/docs/middlewares/routing

**Comment by myml** [comment]
之前也用过gorilla/websocket,难道不是应该找到路由后再执行Upgrade？

**Comment by myml** [comment]
我并没有全局拦截，我甚至没有定义ws路由，但还是被拦截了

**Comment by myml** [comment]
`
		package main
		
		import (
		"log"
		
		"github.com/go-macaron/sockets"
		
		"gopkg.in/macaron.v1"
		)
		type Message struct {
		Id   int
		Name string
		}
		func main() {
		m := macaron.Classic()
		m.Use(sockets.Messages())
		type Message struct {
			Id   int
			Name string
		}
		m.Use(sockets.JSON(Message{}))
		m.Get("/a", func() {
			log.Println("hello")
		})
		m.Run()
		}`

**Comment by Unknwon** [comment]
```
m.Use(sockets.Messages())
    type Message struct {
Id   int
Name string
    }
m.Use(sockets.JSON(Message{}))
```

这不是全局拦截？

**Comment by myml** [comment]
`    m.Use(sockets.JSON(Message{}))`
...这个就是用了全局的？这不是导入websocket中间件吗

**Comment by Unknwon** [comment]
文档并没有说你应该是 `m.Use`.

**Comment by myml** [comment]
你这不按常理出牌啊，我试试

**Comment by Unknwon** [comment]
常理是指。。。？:eyes:

**Comment by myml** [comment]
可以用了，不理你了

**Comment by Unknwon** [comment]
:sweat:
