### ISSUE TITLE
静态文件处理的问题

### ISSUE THREAD

**Issue by cgyy** [go-macaron/macaron#83]
你好，我的问题是这样的:
在项目中这样配置静态文件已 public 开头
```go
	m.Use(macaron.Static("public", macaron.StaticOptions{
		Prefix:      "public",
		SkipLogging: setting.ProdMode,
	}))
```
这样一来，想访问/favicon.ico就只能单独加一个路由:
```go

m.Get("/favicon.ico", func(c *macaron.Context) { c.ServeFileContent("public/favicon.ico") })
```

这个方法
```go

// ServeFileContent serves given file as content to response.
func (ctx *Context) ServeFileContent(file string, names ...string) {
	var name string
	if len(names) > 0 {
		name = names[0]
	} else {
		name = path.Base(file)
	}

	f, err := os.Open(file)
	if err != nil {
		if Env == PROD {
			http.Error(ctx.Resp, "Internal Server Error", 500)
		} else {
			http.Error(ctx.Resp, err.Error(), 500)
		}
		return
	}
	defer f.Close()

	ctx.setRawContentHeader()
	http.ServeContent(ctx.Resp, ctx.Req.Request, name, time.Now(), f)
}
```
最后一行，为什么使用当前时间而不是文件的修改时间，这样会有效率问题吗？
改成这样会不会更好？
 http.ServeContent(ctx.Resp, ctx.Req.Request, name, time.Now(), fi.ModTime())

**Comment by Unknwon** [comment]
...

> http.ServeContent(ctx.Resp, ctx.Req.Request, name, time.Now(), fi.ModTime())

你这行代码有问题。。

多取一次 fi 才更慢吧。。

**Comment by cgyy** [comment]
不好意思，写错了，应该是
```go
http.ServeContent(ctx.Resp, ctx.Req.Request, name,  fi.ModTime(), f)
```
我想说的是如果用 fi.ModTime()，而不直接用当前时间，这样当重复请求一个文件时，服务器直接返回304效率会更好吧？

**Comment by Unknwon** [comment]
`ServeFileContent` 就是为了给最新的资源，防止浏览器不拉取。。

**Comment by Unknwon** [comment]
静态文件就不同了：https://github.com/go-macaron/macaron/blob/master/static.go#L175

**Comment by Unknwon** [comment]
另外只要在 HTML 中指定 favicon 的路径就行了。。

**Comment by cgyy** [comment]
你好，项目里面有多个不同的layout，在html里面指定会导致重复的代码。我改成这样了。
```go
m.Get("/favicon.ico", func(c *macaron.Context) { http.ServeFile(c.Resp, c.Req.Request, "public/favicon.ico") })
```
另外，macaron的方法ServeFileContent我觉得还是有问题,下面这样写会导致浏览器直接下载，而不是
原样显示图片(已确定不是缓存的原因)。用的浏览器是mac上的chrome 48.0.2564.116 (64-bit)
```go
m.Get("/favicon.ico", func(c *macaron.Context) { c.ServeFileContent("public/favicon.ico") })
```

**Comment by Unknwon** [comment]
https://gowalker.org/gopkg.in/macaron.v1#Context_ServeContent

**Comment by Unknwon** [comment]
这个应该是当初的设计初衷问题了。。既然已经有可用的 http 函数，为啥多此一举写一样功能的封装呢。。

**Comment by cgyy** [comment]
这样啊，那我再研究一下吧，多谢~

**Comment by Unknwon** [comment]
:smile:

**Comment by zarte** [comment]
添加路由的方法并不好。配个无前缀同路径的解决。
