### ISSUE TITLE
Recovery 和 Gziper 冲突

### ISSUE THREAD

**Issue by myml** [go-macaron/macaron#87]
Recovery和Gziper的冲突,无法显示panic提示页面，而是弹出浏览器下载页面。

**Comment by myml** [comment]
已找到解决方法，改变两者的注册顺序就可以了，官方文档[注册中间件的最佳顺序](https://go-macaron.com/docs/middlewares#%E6%B3%A8%E5%86%8C%E4%B8%AD%E9%97%B4%E4%BB%B6%E7%9A%84%E6%9C%80%E4%BD%B3%E9%A1%BA%E5%BA%8F)里的顺序是macaron.Logger()
macaron.Recovery()
gzip.Gziper()

**Comment by Unknwon** [comment]
嘿嘿嘿，可以提交个 PR 修复文档
