### ISSUE TITLE
这两个模板引擎速度更快，无闻你看看能不能搞成中间件～

### ISSUE THREAD

**Issue by insionng** [go-macaron/macaron#89]
https://github.com/valyala/fasttemplate
https://github.com/valyala/quicktemplate

**Comment by c4ys** [comment]
既然用模版引擎，速度可能不是最大问题，我觉得编辑器支持对我来说很重要，而django和jinja2现在编辑器支持很好。

**Comment by Unknwon** [comment]
赞同楼上。。
