### ISSUE TITLE
html模板无法使用<!--[if lt IE 9]>标签

### ISSUE THREAD

**Issue by julor** [go-macaron/macaron#92]
使用Go 模板引擎，不能添加<!--[if lt IE 9]>标签。

**Comment by Unknwon** [comment]
怎么使用的代码贴出来

**Comment by julor** [comment]
template_name.html包含：
中间件：m.Use(macaron.Renderer())
模板渲染用：ctx.HTML(200, "template_name")

查了下golang默认模板在选了html时不支持非html标准的标签，比如

**Comment by Unknwon** [comment]
。。那你得提交 issue 到 Go 标准库了。。我这里只是简单的封装 :trollface:
