### ISSUE TITLE
Use "import github.com/go-macaron/macaron" instead of "import gopkg.in/macaron.v1"

### ISSUE THREAD

**Issue by tebanep** [go-macaron/macaron#94]
I think macaron support modules such as session and csfr should refer back to the main package "macaron" as:

github.com/go-macaron/macaron

Instead of:

gopkg.in/macaron.v1

I propose this as there could be problems in depending on a centralized resource, other than github, to resolve macaron's dependencies. There have been some reports lately in twitter about issues happening around gopkg.in:

https://twitter.com/webRat/status/735940872907464704

https://twitter.com/DanielMorsing/status/735959541578358785?lang=es

https://twitter.com/rw_grim/status/748577274069323776

Moreover, this makes sharing a project with other team members more cumbersome, as they will have to install external dependencies in their own workspaces to have it compiled.

Since the standardization of the vendor directory in go 1.6, we have been managing our dependencies in this folder through git submodules and we haven't had any issues in doing that. The great benefit is that we can attach any explicit dependency revision (commit) to our projects and we no longer need any external tools to integrate third party packages in them.

We've been loving macaron and really appreciate how much hassle it removes from our shoulders. Thanks a lot for it! We think that this little fix could make the framework much more stable and thus, encourage greatly its adoption.

**Comment by Unknwon** [comment]
Hi, thanks your feedback! 

At this point, gopkg.in is back online already, GitHub downs pretty often these days, it feels the same to me.

**Comment by tebanep** [comment]
If it doesn't bother you, would you mind if i make a pull request with the changes or would you rather keep the repositories as they are today, using gopkg.in?

**Comment by Unknwon** [comment]
`gopkg.in/macaron.v1` has been widely used, it is not a good idea to change it.
