### ISSUE TITLE
Route with integer regex

### ISSUE THREAD

**Issue by ysaakpr** [go-macaron/macaron#95]
```
m.Get("/:id([0-9]+)", GetOrder)
m.Get("/:id:string", GetOrderString)

```
/qwerty123 supposed to be matched with GetOrderString, but matching with GetOrder.

Can you tell me why

**Comment by Unknwon** [comment]
Please see https://github.com/go-macaron/docs/issues/7

**Comment by ysaakpr** [comment]
Thank you....So its indented to behave like this...Awesome, better to add this to the documentation
