### ISSUE TITLE
组路由中间件不生效

### ISSUE THREAD

**Issue by myml** [go-macaron/macaron#98]
`

	mm := macaron.Classic()
	mm.Group("/api", func() {

	}, func(ctx *macaron.Context) {
		log.Println("中间件")
	})
	mm.Run()
`

组路由添加的集体中间件好像并没有运行

**Comment by Unknwon** [comment]
你并无任何路由注册为什么要运行？

**Comment by myml** [comment]
我想实现当访问这个组路由里的任何路由都执行一个macaron.Handler应该怎么做呢

**Comment by Unknwon** [comment]
没有理由不会执行任何中间件。

**Comment by myml** [comment]
类似macaron.Logger(),gzip.Gziper(),这种中间件,在用Use全局注册后,可以自动执行

**Comment by Unknwon** [comment]
没有路由被注册那执行中间件的意义是什么？

**Comment by myml** [comment]
我想利用toolbox来实现自动化的路由统计

**Comment by Unknwon** [comment]
我不懂你的逻辑

**Comment by myml** [comment]
`
ctx *macaron.Context, t toolbox.Toolbox) {
	start := time.Now()
	defer func() {
		t.AddStatistics(ctx.Req.Method, ctx.Req.URL.Path, time.Since(start))
	}()
	ctx.Next()
`
类似这种

**Comment by Unknwon** [comment]
https://go-macaron.com/docs/intro/core_concepts#%E5%A4%84%E7%90%86%E5%99%A8%E5%B7%A5%E4%BD%9C%E6%B5%81

**Comment by myml** [comment]
你是想说路由先于中间件执行吗?我测试的结果是中间件早于路由的执行

**Comment by myml** [comment]
是想告诉我可以用m.Before吗,我不擅长看流程图

**Comment by myml** [comment]
因为before是func(rw http.ResponseWriter, req *http.Request)bool这种形式的,没法使用其它中间件,所有就用了Use来注册,功能是实现了,但是我想能实现统计组路由的话效率会更高些
